version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  # Server 1
  wordcount_server_1:
    build: ./server
    environment:
      - SERVER_PORT=18812
      - REDIS_HOST=redis
    ports:
      - "18812:18812"
    depends_on:
      - redis

  # Server 2
  wordcount_server_2:
    build: ./server
    environment:
      - SERVER_PORT=18813
      - REDIS_HOST=redis
    ports:
      - "18813:18813"
    depends_on:
      - redis

  # Server 3
  wordcount_server_3:
    build: ./server
    environment:
      - SERVER_PORT=18814
      - REDIS_HOST=redis
    ports:
      - "18814:18814"
    depends_on:
      - redis

  client:
    build: ./client
    depends_on:
      - wordcount_server_1
      - wordcount_server_2
      - wordcount_server_3
